repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files

- repo: git://github.com/nakt/pre-commit-makefile
  rev: master
  hooks:
    - id: makefile-doc
